# Travis can building for Linux and macOS
matrix:
  include:
    # To maximise compatibility pick earliest image, OS X 10.10 Yosemite
    - os: osx
      osx_image: xcode6.4
      sudo: required
      language: generic

before_install:
  # OS and default Python info
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sw_vers; fi

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl
  - PROJECT_DIR="$PWD"
  - echo $PROJECT_DIR
  - mkdir upload

script:
  # Download and build Python
  - cd "$PROJECT_DIR"
  - sh build_python.sh

  # Compress and upload it before touching it
  - cd "$PROJECT_DIR"
  - tar czf upload/python3-full.tar.gz python-portable/
  - curl --upload-file ./upload/python3-full.tar.gz https://transfer.sh/python3-full.tar.gz | tee -a output_urls.txt && echo "" >> output_urls.txt

  # Check built Python
  - cd "$PROJECT_DIR"
  - du -sk python-portable/
  - cd python-portable
  - otool -L bin/python3.6
  - ./bin/python3.6 -c 'import ssl; print(ssl.OPENSSL_VERSION)'
  - ./bin/python3.6 -m pip --version

  # Reduce stand-alone Python and upload it
  - cd "$PROJECT_DIR"
  - python process_python_build.py "$PROJECT_DIR/python-portable"
  - tar czf upload/python3-reduced.tar.gz python-portable/
  - curl --upload-file ./upload/python3-reduced.tar.gz https://transfer.sh/python3-reduced.tar.gz | tee -a output_urls.txt && echo "" >> output_urls.txt

  # Print all uploaded files URLs
  - cd "$PROJECT_DIR"
  - cat output_urls.txt
